### PR TITLE
Don't Redownload Composer

### PR DESCRIPTION
**Pull request by mloberg**
There's been some really good changes in composer (https://github.com/composer/composer/commit/ac676f47f7bbc619678a29deae097b6b0710b799) that make it tons faster then before, but running Boxen will revert composer to before these changes. So instead of forcing a version, just leave composer alone if it's already installed.

### CODE REVIEW

**Comment by mattheath** [comment]
Thanks @mloberg, this looks fine - though we could tighten up the `unless` condition to use `creates` as we're only checking for file existence now?

Also might be worth bumping the version to `alpha9` so this change is included if the user doesn't have composer already?

**Comment by mloberg** [comment]
It was a quick fix, but creates makes more sense. I'll update it.

With this change though, any users with existing composer installs will
stay at alpha8. One option might be using hiera which would allow a
default, but could also be be overridden by the user.

**Comment by mattheath** [comment]
Hiera would be ideal, but it would likely be a bit more work to update now. Happy for that to be done separately if someone (you? :wink:) wants to pick it up.

**Comment by mloberg** [comment]
I could definitely start some work on it when I have some time.

**Comment by sambauers** [comment]
Hiera for configs is part of the nascent v2.0 plans - https://github.com/boxen/puppet-php/pull/56 - maybe contribute changes to the v2 branch to override composer version and checksum?

**Comment by mattheath** [comment]
That would be perfect :+1:

**Comment by sambauers** [comment]
I've made an attempt at this via Hiera configs in my existing v2 branch PR. Changeset is here - https://github.com/sambauers/puppet-php/commit/84612e76c1d2424e826814f0333de6acece866d5

**Comment by sambauers** [comment]
This is covered in the v2 branch now, suggest we close this.

**Comment by mloberg** [comment]
Sounds good to me.

**Pull request closed without merging**
