### PR TITLE
Remove version based PHP and PHP::FPM classes.

### PR DESCRIPTION
**Pull request by sambauers**

### CODE REVIEW

**Comment by sambauers** [comment]
@mattheath - I think this works. If a user specifies a major or minor version for 'x' in `php::version { 'x' }`, then it will default to the latest secure version (minor version sensitive).

**Comment by sambauers** [comment]
Added Major/Minor version fallback to `php::fpm { 'x': }` as well. Moved secure version listings to Hiera so they can be configured by the user.

**Comment by sambauers** [comment]
I'll leave this PR at these changes so they can be reviewed and merged more efficiently.

**Comment by mattheath** [comment]
:+1:

**Pull request merged**
