### PR TITLE
Update PHP versions, use Hiera for configs, allow configure params on PHP builds, add PThreads extension, update tests.

### PR DESCRIPTION
**Pull request by sambauers**
This was originally here - https://github.com/mattheath/puppet-php/pull/58

### CODE REVIEW

**Comment by sambauers** [comment]
My thoughts on notes from old PR:
* **Version specific classes**: would be great to remove, is breaking the syntax a big deal? i.e. `include php::5_3_17` versus `include php { '5.3.17': }`
* **Keeping track of latest versions**: just about every PHP release has a CVE fix. This is just a small tweak when you are already maintaining version specific classes, but might seem a chore if you aren't. I think it's kind of important as the dev version of PHP usually influences the deployed production version.

**Comment by sambauers** [comment]
Once this is merged I promise I'll stop making pull requests off my master branch.

**Comment by sambauers** [comment]
The Ruby 1.8.7 build died because of a random Gem install error at Travis.

Does 1.8.7 really need to be tested? Should there be tests against newer Ruby versions instead or as well?

**Comment by mattheath** [comment]
Ruby 1.8.7 was the system ruby on Mountain Lion, which was then changed to 2.0.0+ on Mavericks. Boxen uses the system ruby, and I think Boxen still supports Mountain Lion? So we likely need to test this still. I'll give travis a kick and see what happens.

If we increment the major version of this module to `2.0.0`, I think we can break syntax going forward. Other language modules have changed their external API as they developed and this would bring this module in line with the other modules. It would also mean there would be less maintenance required going forwards (which I would like as I no longer use PHP! :wink:). Happy to merge this first though, and tackle separately.

I'm still uncertain on the secure versions - once a CVE patch is released and a version becomes insecure we would need to bump the version in this module, and therefore re-tag a new version. Unless people upgrade their boxen modules frequently they won't see these changes? Also as far as I'm aware certain PHP distributions have backported security patches without incrementing the versions? I'm likely out of touch on this one, so I'll leave it to you!

**Comment by sambauers** [comment]
Let's merge this all in then start hacking. I'm guessing we would start with removing the versioned classes (and updating the comments and docs to reflect that).

**Comment by sambauers** [comment]
Also, I'm not using PHP much either these days :grin:

**Comment by mattheath** [comment]
Thanks for your amazing work! :boom: :+1:

**Pull request merged**
