### PR TITLE
Fix php_require function, bump PHP secure versions.

### PR DESCRIPTION
**Pull request by sambauers**

### CODE REVIEW

**Comment by sambauers** [comment]
This also fixes https://github.com/boxen/puppet-php/issues/67

**Comment by sambauers** [comment]
@mattheath, this is a pretty bad bug, and worth a patch release to 2.0.1 in my opinion.

**Comment by mattheath** [comment]
Agreed, thanks for fixing! :+1:

**Comment by mattheath** [comment]
Release tagged as `2.0.1`

**Pull request merged**
