### PR TITLE
Update CHANGELOG, bump secure PHP versions, add secure warning toggle, upgrade instructions.

### PR DESCRIPTION
**Pull request by sambauers**

### CODE REVIEW

**Comment by sambauers** [comment]
@mattheath - I think this is just about everything I want to throw at this. How do you want to proceed with release? Do you want to go through a release candidate process?

**Comment by sambauers** [comment]
@mattheath, any progress here?

**Comment by sambauers** [comment]
@mattheath, still bumping version numbers and keeping this PR up to date

**Comment by mattheath** [comment]
Sorry @sambauers! Let's get this merged, and I'll tag a new release. Thank you so much for all your work on this!

**Pull request merged**
