### PR TITLE
V2

### PR DESCRIPTION
**Pull request by mattheath**
Brings PHP module up to date, and more in line with other Boxen modules /cc @sambauers

 * Use Hiera for configs
 * Allow configure params on PHP builds
 * Add PThreads extension
 * Update cardboard to 2.1.0 and update tests
 * Add support for PHP 5.6+
 * Add insecure PHP version warnings
 * Make Composer version configurable
 * Remove version specific PHP classes allowing arbitrary PHP versions

Think we're good to go on this. It looks great!

### CODE REVIEW

**Comment by sambauers** [comment]
:+1: @mattheath

**Comment by mattheath** [comment]
Tagged and released as `2.0.0`

**Comment by gblair** [comment]
This looks awesome - thanks guys! :bow:

**Comment by sambauers** [comment]
Thanks, nice to be noticed! It was a good "Getting to know Puppet" project.

**Pull request merged**
