### PR TITLE
Update composer to 1.2.0

### PR DESCRIPTION
**Pull request by alexmace**

### CODE REVIEW

**Comment by jacobbednarz** [comment]
LGTM ⭐

**Comment by jacobbednarz** [comment]
Where did you get the checksum from? I get different results for the `1.2.0` release.

```
$ md5 -q ~/Downloads/composer.phar
df47dc307fa614daa5a10423bdf4e1bb
```

**Comment by alexmace** [comment]
I used shasum to generate the hash:

% shasum ~/Downloads/composer.phar                                                                                       !10484
ad898f510e1a7909fe251d2193a8cca1257e9dd4  /Users/amace/Downloads/composer.phar

I’m assuming this is correct since it installs without complaining about the checksum, but I haven’t looked under the hood to ensure that is how it is calculated.

**Comment by alexmace** [comment]
Ah, I've looked under the hood now and I can see it only uses the checksum to see if it should download composer again, and it does indeed use md5. I'll update the PR.

**Comment by jacobbednarz** [comment]
LGTM :ship:

**Pull request merged**
